-- Auto-generated from data/fixtures-2026.json
-- Do not edit by hand; regenerate via scripts/generate-fixtures.ts

-- TEAMS
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Mexico', 'A', '🇲🇽', 'MEX') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('South Africa', 'A', '🇿🇦', 'RSA') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('South Korea', 'A', '🇰🇷', 'KOR') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Czechia', 'A', '🇨🇿', 'CZE') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Canada', 'B', '🇨🇦', 'CAN') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Bosnia and Herzegovina', 'B', '🇧🇦', 'BIH') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Qatar', 'B', '🇶🇦', 'QAT') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Switzerland', 'B', '🇨🇭', 'SUI') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Brazil', 'C', '🇧🇷', 'BRA') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Morocco', 'C', '🇲🇦', 'MAR') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Haiti', 'C', '🇭🇹', 'HAI') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Scotland', 'C', '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'SCO') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('USA', 'D', '🇺🇸', 'USA') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Paraguay', 'D', '🇵🇾', 'PAR') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Australia', 'D', '🇦🇺', 'AUS') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Türkiye', 'D', '🇹🇷', 'TUR') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Germany', 'E', '🇩🇪', 'GER') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Curaçao', 'E', '🇨🇼', 'CUW') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Ivory Coast', 'E', '🇨🇮', 'CIV') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Ecuador', 'E', '🇪🇨', 'ECU') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Netherlands', 'F', '🇳🇱', 'NED') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Japan', 'F', '🇯🇵', 'JPN') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Sweden', 'F', '🇸🇪', 'SWE') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Tunisia', 'F', '🇹🇳', 'TUN') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Belgium', 'G', '🇧🇪', 'BEL') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Egypt', 'G', '🇪🇬', 'EGY') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Iran', 'G', '🇮🇷', 'IRN') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('New Zealand', 'G', '🇳🇿', 'NZL') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Spain', 'H', '🇪🇸', 'ESP') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Cape Verde', 'H', '🇨🇻', 'CPV') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Saudi Arabia', 'H', '🇸🇦', 'KSA') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Uruguay', 'H', '🇺🇾', 'URU') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('France', 'I', '🇫🇷', 'FRA') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Senegal', 'I', '🇸🇳', 'SEN') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Iraq', 'I', '🇮🇶', 'IRQ') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Norway', 'I', '🇳🇴', 'NOR') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Argentina', 'J', '🇦🇷', 'ARG') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Algeria', 'J', '🇩🇿', 'ALG') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Austria', 'J', '🇦🇹', 'AUT') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Jordan', 'J', '🇯🇴', 'JOR') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Portugal', 'K', '🇵🇹', 'POR') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('DR Congo', 'K', '🇨🇩', 'COD') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Uzbekistan', 'K', '🇺🇿', 'UZB') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Colombia', 'K', '🇨🇴', 'COL') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('England', 'L', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'ENG') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Croatia', 'L', '🇭🇷', 'CRO') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Ghana', 'L', '🇬🇭', 'GHA') on conflict (name) do nothing;
insert into teams (name, group_code, flag_emoji, fifa_code) values ('Panama', 'L', '🇵🇦', 'PAN') on conflict (name) do nothing;

-- GROUP MATCHES (72)
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'A', (select id from teams where name='Mexico'), (select id from teams where name='South Africa'), '2026-06-11T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'A', (select id from teams where name='South Korea'), (select id from teams where name='Czechia'), '2026-06-11T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'A', (select id from teams where name='Mexico'), (select id from teams where name='South Korea'), '2026-06-15T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'A', (select id from teams where name='South Africa'), (select id from teams where name='Czechia'), '2026-06-15T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'A', (select id from teams where name='Mexico'), (select id from teams where name='Czechia'), '2026-06-19T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'A', (select id from teams where name='South Africa'), (select id from teams where name='South Korea'), '2026-06-19T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'B', (select id from teams where name='Canada'), (select id from teams where name='Bosnia and Herzegovina'), '2026-06-12T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'B', (select id from teams where name='Qatar'), (select id from teams where name='Switzerland'), '2026-06-12T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'B', (select id from teams where name='Canada'), (select id from teams where name='Qatar'), '2026-06-16T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'B', (select id from teams where name='Bosnia and Herzegovina'), (select id from teams where name='Switzerland'), '2026-06-16T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'B', (select id from teams where name='Canada'), (select id from teams where name='Switzerland'), '2026-06-20T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'B', (select id from teams where name='Bosnia and Herzegovina'), (select id from teams where name='Qatar'), '2026-06-20T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'C', (select id from teams where name='Brazil'), (select id from teams where name='Morocco'), '2026-06-13T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'C', (select id from teams where name='Haiti'), (select id from teams where name='Scotland'), '2026-06-13T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'C', (select id from teams where name='Brazil'), (select id from teams where name='Haiti'), '2026-06-17T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'C', (select id from teams where name='Morocco'), (select id from teams where name='Scotland'), '2026-06-17T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'C', (select id from teams where name='Brazil'), (select id from teams where name='Scotland'), '2026-06-21T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'C', (select id from teams where name='Morocco'), (select id from teams where name='Haiti'), '2026-06-21T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'D', (select id from teams where name='USA'), (select id from teams where name='Paraguay'), '2026-06-14T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'D', (select id from teams where name='Australia'), (select id from teams where name='Türkiye'), '2026-06-14T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'D', (select id from teams where name='USA'), (select id from teams where name='Australia'), '2026-06-18T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'D', (select id from teams where name='Paraguay'), (select id from teams where name='Türkiye'), '2026-06-18T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'D', (select id from teams where name='USA'), (select id from teams where name='Türkiye'), '2026-06-22T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'D', (select id from teams where name='Paraguay'), (select id from teams where name='Australia'), '2026-06-22T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'E', (select id from teams where name='Germany'), (select id from teams where name='Curaçao'), '2026-06-15T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'E', (select id from teams where name='Ivory Coast'), (select id from teams where name='Ecuador'), '2026-06-15T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'E', (select id from teams where name='Germany'), (select id from teams where name='Ivory Coast'), '2026-06-19T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'E', (select id from teams where name='Curaçao'), (select id from teams where name='Ecuador'), '2026-06-19T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'E', (select id from teams where name='Germany'), (select id from teams where name='Ecuador'), '2026-06-23T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'E', (select id from teams where name='Curaçao'), (select id from teams where name='Ivory Coast'), '2026-06-23T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'F', (select id from teams where name='Netherlands'), (select id from teams where name='Japan'), '2026-06-16T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'F', (select id from teams where name='Sweden'), (select id from teams where name='Tunisia'), '2026-06-16T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'F', (select id from teams where name='Netherlands'), (select id from teams where name='Sweden'), '2026-06-20T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'F', (select id from teams where name='Japan'), (select id from teams where name='Tunisia'), '2026-06-20T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'F', (select id from teams where name='Netherlands'), (select id from teams where name='Tunisia'), '2026-06-24T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'F', (select id from teams where name='Japan'), (select id from teams where name='Sweden'), '2026-06-24T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'G', (select id from teams where name='Belgium'), (select id from teams where name='Egypt'), '2026-06-17T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'G', (select id from teams where name='Iran'), (select id from teams where name='New Zealand'), '2026-06-17T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'G', (select id from teams where name='Belgium'), (select id from teams where name='Iran'), '2026-06-21T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'G', (select id from teams where name='Egypt'), (select id from teams where name='New Zealand'), '2026-06-21T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'G', (select id from teams where name='Belgium'), (select id from teams where name='New Zealand'), '2026-06-25T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'G', (select id from teams where name='Egypt'), (select id from teams where name='Iran'), '2026-06-25T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'H', (select id from teams where name='Spain'), (select id from teams where name='Cape Verde'), '2026-06-18T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'H', (select id from teams where name='Saudi Arabia'), (select id from teams where name='Uruguay'), '2026-06-18T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'H', (select id from teams where name='Spain'), (select id from teams where name='Saudi Arabia'), '2026-06-22T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'H', (select id from teams where name='Cape Verde'), (select id from teams where name='Uruguay'), '2026-06-22T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'H', (select id from teams where name='Spain'), (select id from teams where name='Uruguay'), '2026-06-26T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'H', (select id from teams where name='Cape Verde'), (select id from teams where name='Saudi Arabia'), '2026-06-26T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'I', (select id from teams where name='France'), (select id from teams where name='Senegal'), '2026-06-19T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'I', (select id from teams where name='Iraq'), (select id from teams where name='Norway'), '2026-06-19T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'I', (select id from teams where name='France'), (select id from teams where name='Iraq'), '2026-06-23T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'I', (select id from teams where name='Senegal'), (select id from teams where name='Norway'), '2026-06-23T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'I', (select id from teams where name='France'), (select id from teams where name='Norway'), '2026-06-27T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'I', (select id from teams where name='Senegal'), (select id from teams where name='Iraq'), '2026-06-27T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'J', (select id from teams where name='Argentina'), (select id from teams where name='Algeria'), '2026-06-20T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'J', (select id from teams where name='Austria'), (select id from teams where name='Jordan'), '2026-06-20T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'J', (select id from teams where name='Argentina'), (select id from teams where name='Austria'), '2026-06-24T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'J', (select id from teams where name='Algeria'), (select id from teams where name='Jordan'), '2026-06-24T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'J', (select id from teams where name='Argentina'), (select id from teams where name='Jordan'), '2026-06-28T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'J', (select id from teams where name='Algeria'), (select id from teams where name='Austria'), '2026-06-28T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'K', (select id from teams where name='Portugal'), (select id from teams where name='DR Congo'), '2026-06-21T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'K', (select id from teams where name='Uzbekistan'), (select id from teams where name='Colombia'), '2026-06-21T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'K', (select id from teams where name='Portugal'), (select id from teams where name='Uzbekistan'), '2026-06-25T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'K', (select id from teams where name='DR Congo'), (select id from teams where name='Colombia'), '2026-06-25T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'K', (select id from teams where name='Portugal'), (select id from teams where name='Colombia'), '2026-06-29T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'K', (select id from teams where name='DR Congo'), (select id from teams where name='Uzbekistan'), '2026-06-29T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'L', (select id from teams where name='England'), (select id from teams where name='Croatia'), '2026-06-22T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'L', (select id from teams where name='Ghana'), (select id from teams where name='Panama'), '2026-06-22T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'L', (select id from teams where name='England'), (select id from teams where name='Ghana'), '2026-06-26T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'L', (select id from teams where name='Croatia'), (select id from teams where name='Panama'), '2026-06-26T22:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'L', (select id from teams where name='England'), (select id from teams where name='Panama'), '2026-06-30T19:00:00.000Z');
insert into matches (stage, group_code, home_team_id, away_team_id, kickoff) values ('group', 'L', (select id from teams where name='Croatia'), (select id from teams where name='Ghana'), '2026-06-30T22:00:00.000Z');

-- KNOCKOUT SLOTS (team_ids null until admin assigns)
insert into matches (stage, knockout_slot, kickoff) values ('R32', 'R32-1', '2026-06-29T19:00:00.000Z');
insert into matches (stage, knockout_slot, kickoff) values ('R32', 'R32-2', '2026-06-29T22:00:00.000Z');
insert into matches (stage, knockout_slot, kickoff) values ('R32', 'R32-3', '2026-06-29T19:00:00.000Z');
insert into matches (stage, knockout_slot, kickoff) values ('R32', 'R32-4', '2026-06-29T22:00:00.000Z');
insert into matches (stage, knockout_slot, kickoff) values ('R32', 'R32-5', '2026-06-29T19:00:00.000Z');
insert into matches (stage, knockout_slot, kickoff) values ('R32', 'R32-6', '2026-06-29T22:00:00.000Z');
insert into matches (stage, knockout_slot, kickoff) values ('R32', 'R32-7', '2026-06-29T19:00:00.000Z');
insert into matches (stage, knockout_slot, kickoff) values ('R32', 'R32-8', '2026-06-29T22:00:00.000Z');
insert into matches (stage, knockout_slot, kickoff) values ('R32', 'R32-9', '2026-06-29T19:00:00.000Z');
insert into matches (stage, knockout_slot, kickoff) values ('R32', 'R32-10', '2026-06-29T22:00:00.000Z');
insert into matches (stage, knockout_slot, kickoff) values ('R32', 'R32-11', '2026-06-29T19:00:00.000Z');
insert into matches (stage, knockout_slot, kickoff) values ('R32', 'R32-12', '2026-06-29T22:00:00.000Z');
insert into matches (stage, knockout_slot, kickoff) values ('R32', 'R32-13', '2026-06-29T19:00:00.000Z');
insert into matches (stage, knockout_slot, kickoff) values ('R32', 'R32-14', '2026-06-29T22:00:00.000Z');
insert into matches (stage, knockout_slot, kickoff) values ('R32', 'R32-15', '2026-06-29T19:00:00.000Z');
insert into matches (stage, knockout_slot, kickoff) values ('R32', 'R32-16', '2026-06-29T22:00:00.000Z');
insert into matches (stage, knockout_slot, kickoff) values ('R16', 'R16-1', '2026-07-05T22:00:00.000Z');
insert into matches (stage, knockout_slot, kickoff) values ('R16', 'R16-2', '2026-07-05T19:00:00.000Z');
insert into matches (stage, knockout_slot, kickoff) values ('R16', 'R16-3', '2026-07-05T22:00:00.000Z');
insert into matches (stage, knockout_slot, kickoff) values ('R16', 'R16-4', '2026-07-05T19:00:00.000Z');
insert into matches (stage, knockout_slot, kickoff) values ('R16', 'R16-5', '2026-07-05T22:00:00.000Z');
insert into matches (stage, knockout_slot, kickoff) values ('R16', 'R16-6', '2026-07-05T19:00:00.000Z');
insert into matches (stage, knockout_slot, kickoff) values ('R16', 'R16-7', '2026-07-05T22:00:00.000Z');
insert into matches (stage, knockout_slot, kickoff) values ('R16', 'R16-8', '2026-07-05T19:00:00.000Z');
insert into matches (stage, knockout_slot, kickoff) values ('QF', 'QF-1', '2026-07-11T22:00:00.000Z');
insert into matches (stage, knockout_slot, kickoff) values ('QF', 'QF-2', '2026-07-11T19:00:00.000Z');
insert into matches (stage, knockout_slot, kickoff) values ('QF', 'QF-3', '2026-07-11T22:00:00.000Z');
insert into matches (stage, knockout_slot, kickoff) values ('QF', 'QF-4', '2026-07-11T19:00:00.000Z');
insert into matches (stage, knockout_slot, kickoff) values ('SF', 'SF-1', '2026-07-16T22:00:00.000Z');
insert into matches (stage, knockout_slot, kickoff) values ('SF', 'SF-2', '2026-07-16T19:00:00.000Z');
insert into matches (stage, knockout_slot, kickoff) values ('3rd', '3rd-1', '2026-07-20T22:00:00.000Z');
insert into matches (stage, knockout_slot, kickoff) values ('final', 'final-1', '2026-07-21T22:00:00.000Z');
