-- Curated top-3 likely goal scorers per team (144 total).
-- Admin can add more via the admin page or direct inserts as squads are finalized.
-- Safe to re-run: no-ops if the (team_id, name) combo already exists.

create unique index if not exists players_team_name_uidx on players(team_id, name);

-- Helper: insert a player by looking up team by name
-- Format: ('Player Name', 'Team Name')
-- We inline rather than use a function so this is a single transactional migration.

with seed(name, team) as (values
  -- Group A
  ('Raúl Jiménez',              'Mexico'),
  ('Santiago Giménez',          'Mexico'),
  ('Hirving Lozano',            'Mexico'),
  ('Percy Tau',                 'South Africa'),
  ('Lyle Foster',               'South Africa'),
  ('Themba Zwane',              'South Africa'),
  ('Son Heung-min',             'South Korea'),
  ('Hwang Hee-chan',            'South Korea'),
  ('Lee Kang-in',               'South Korea'),
  ('Patrik Schick',             'Czechia'),
  ('Adam Hložek',               'Czechia'),
  ('Tomáš Souček',              'Czechia'),
  -- Group B
  ('Jonathan David',            'Canada'),
  ('Alphonso Davies',           'Canada'),
  ('Cyle Larin',                'Canada'),
  ('Edin Džeko',                'Bosnia and Herzegovina'),
  ('Ermedin Demirović',         'Bosnia and Herzegovina'),
  ('Haris Tabaković',           'Bosnia and Herzegovina'),
  ('Akram Afif',                'Qatar'),
  ('Almoez Ali',                'Qatar'),
  ('Hassan Al-Haydos',          'Qatar'),
  ('Breel Embolo',              'Switzerland'),
  ('Xherdan Shaqiri',           'Switzerland'),
  ('Zeki Amdouni',              'Switzerland'),
  -- Group C
  ('Vinícius Júnior',           'Brazil'),
  ('Rodrygo',                   'Brazil'),
  ('Raphinha',                  'Brazil'),
  ('Hakim Ziyech',              'Morocco'),
  ('Youssef En-Nesyri',         'Morocco'),
  ('Achraf Hakimi',             'Morocco'),
  ('Duckens Nazon',             'Haiti'),
  ('Frantzdy Pierrot',          'Haiti'),
  ('Derrick Etienne',           'Haiti'),
  ('Scott McTominay',           'Scotland'),
  ('Che Adams',                 'Scotland'),
  ('John McGinn',               'Scotland'),
  -- Group D
  ('Christian Pulisic',         'USA'),
  ('Folarin Balogun',           'USA'),
  ('Timothy Weah',              'USA'),
  ('Miguel Almirón',            'Paraguay'),
  ('Julio Enciso',              'Paraguay'),
  ('Antonio Sanabria',          'Paraguay'),
  ('Mitchell Duke',             'Australia'),
  ('Aaron Mooy',                'Australia'),
  ('Mathew Leckie',             'Australia'),
  ('Kenan Yıldız',              'Türkiye'),
  ('Arda Güler',                'Türkiye'),
  ('Hakan Çalhanoğlu',          'Türkiye'),
  -- Group E
  ('Jamal Musiala',             'Germany'),
  ('Kai Havertz',               'Germany'),
  ('Florian Wirtz',             'Germany'),
  ('Leandro Bacuna',            'Curaçao'),
  ('Tahith Chong',              'Curaçao'),
  ('Juninho Bacuna',            'Curaçao'),
  ('Sébastien Haller',          'Ivory Coast'),
  ('Simon Adingra',             'Ivory Coast'),
  ('Nicolas Pépé',              'Ivory Coast'),
  ('Moisés Caicedo',            'Ecuador'),
  ('Enner Valencia',            'Ecuador'),
  ('Kendry Páez',               'Ecuador'),
  -- Group F
  ('Cody Gakpo',                'Netherlands'),
  ('Memphis Depay',             'Netherlands'),
  ('Xavi Simons',               'Netherlands'),
  ('Kaoru Mitoma',              'Japan'),
  ('Takefusa Kubo',             'Japan'),
  ('Ayase Ueda',                'Japan'),
  ('Alexander Isak',            'Sweden'),
  ('Viktor Gyökeres',           'Sweden'),
  ('Dejan Kulusevski',          'Sweden'),
  ('Youssef Msakni',            'Tunisia'),
  ('Wahbi Khazri',              'Tunisia'),
  ('Hannibal Mejbri',           'Tunisia'),
  -- Group G
  ('Romelu Lukaku',             'Belgium'),
  ('Jérémy Doku',               'Belgium'),
  ('Kevin De Bruyne',           'Belgium'),
  ('Mohamed Salah',             'Egypt'),
  ('Mostafa Mohamed',           'Egypt'),
  ('Omar Marmoush',             'Egypt'),
  ('Mehdi Taremi',              'Iran'),
  ('Sardar Azmoun',             'Iran'),
  ('Alireza Jahanbakhsh',       'Iran'),
  ('Chris Wood',                'New Zealand'),
  ('Sarpreet Singh',            'New Zealand'),
  ('Ben Waine',                 'New Zealand'),
  -- Group H
  ('Lamine Yamal',              'Spain'),
  ('Nico Williams',             'Spain'),
  ('Álvaro Morata',             'Spain'),
  ('Jovane Cabral',             'Cape Verde'),
  ('Ryan Mendes',               'Cape Verde'),
  ('Bebé',                      'Cape Verde'),
  ('Salem Al-Dawsari',          'Saudi Arabia'),
  ('Firas Al-Buraikan',         'Saudi Arabia'),
  ('Saleh Al-Shehri',           'Saudi Arabia'),
  ('Darwin Núñez',              'Uruguay'),
  ('Federico Valverde',         'Uruguay'),
  ('Facundo Pellistri',         'Uruguay'),
  -- Group I
  ('Kylian Mbappé',             'France'),
  ('Ousmane Dembélé',           'France'),
  ('Antoine Griezmann',         'France'),
  ('Sadio Mané',                'Senegal'),
  ('Ismaïla Sarr',              'Senegal'),
  ('Nicolas Jackson',           'Senegal'),
  ('Aymen Hussein',             'Iraq'),
  ('Mohanad Ali',               'Iraq'),
  ('Ali Al-Hamadi',             'Iraq'),
  ('Erling Haaland',            'Norway'),
  ('Martin Ødegaard',           'Norway'),
  ('Alexander Sørloth',         'Norway'),
  -- Group J
  ('Lionel Messi',              'Argentina'),
  ('Lautaro Martínez',          'Argentina'),
  ('Julián Álvarez',            'Argentina'),
  ('Riyad Mahrez',              'Algeria'),
  ('Islam Slimani',             'Algeria'),
  ('Baghdad Bounedjah',         'Algeria'),
  ('Marko Arnautović',          'Austria'),
  ('Michael Gregoritsch',       'Austria'),
  ('Christoph Baumgartner',     'Austria'),
  ('Musa Al-Tamari',            'Jordan'),
  ('Yazan Al-Naimat',           'Jordan'),
  ('Ali Olwan',                 'Jordan'),
  -- Group K
  ('Cristiano Ronaldo',         'Portugal'),
  ('Bruno Fernandes',           'Portugal'),
  ('Rafael Leão',               'Portugal'),
  ('Cédric Bakambu',            'DR Congo'),
  ('Yoane Wissa',               'DR Congo'),
  ('Silas Katompa',             'DR Congo'),
  ('Eldor Shomurodov',          'Uzbekistan'),
  ('Oston Urunov',              'Uzbekistan'),
  ('Azizbek Turgunboev',        'Uzbekistan'),
  ('Luis Díaz',                 'Colombia'),
  ('Jhon Durán',                'Colombia'),
  ('James Rodríguez',           'Colombia'),
  -- Group L
  ('Harry Kane',                'England'),
  ('Bukayo Saka',               'England'),
  ('Jude Bellingham',           'England'),
  ('Andrej Kramarić',           'Croatia'),
  ('Bruno Petković',            'Croatia'),
  ('Mateo Kovačić',             'Croatia'),
  ('Mohammed Kudus',            'Ghana'),
  ('Jordan Ayew',               'Ghana'),
  ('Antoine Semenyo',           'Ghana'),
  ('José Fajardo',              'Panama'),
  ('Cecilio Waterman',          'Panama'),
  ('Ismael Díaz',               'Panama')
)
insert into players (name, team_id)
select s.name, t.id
from seed s
join teams t on t.name = s.team
on conflict (team_id, name) do nothing;
