-- WC 2026 squads — first batch (confirmed as of 2026-05-30).
-- Run on BOTH Supabase projects (family + work).
--
-- 30 squads confirmed below (~770 players). 18 still pending and will be added
-- in a follow-up migration once federations publish them:
--   Group A: Mexico, Czechia
--   Group B: Canada, Qatar
--   Group C: Morocco
--   Group D: Australia, Paraguay, Türkiye
--   Group E: Ecuador
--   Group G: Egypt, Iran
--   Group H: Saudi Arabia, Uruguay
--   Group I: Iraq
--   Group J: Algeria, Jordan
--   Group K: Uzbekistan
--   Group L: Ghana
--
-- `on conflict (team_id, name) do nothing` skips duplicates (e.g. names already
-- in the curated 144 from 0004). Safe to re-run.

with seed(name, team) as (values
  -- Group A · South Africa
  ('Ronwen Williams',         'South Africa'),
  ('Ricardo Goss',            'South Africa'),
  ('Sipho Chaine',            'South Africa'),
  ('Aubrey Modiba',           'South Africa'),
  ('Khuliso Mudau',           'South Africa'),
  ('Nkosinathi Sibisi',       'South Africa'),
  ('Mbekezeli Mbokazi',       'South Africa'),
  ('Ime Okon',                'South Africa'),
  ('Samukele Kabini',         'South Africa'),
  ('Khulumani Ndamane',       'South Africa'),
  ('Thabang Matuludi',        'South Africa'),
  ('Kamogelo Sebelebele',     'South Africa'),
  ('Bradley Cross',           'South Africa'),
  ('Olwethu Makhanya',        'South Africa'),
  ('Teboho Mokoena',          'South Africa'),
  ('Sphephelo Sithole',       'South Africa'),
  ('Thalente Mbatha',         'South Africa'),
  ('Jayden Adams',            'South Africa'),
  ('Themba Zwane',            'South Africa'),
  ('Lyle Foster',             'South Africa'),
  ('Evidence Makgopa',        'South Africa'),
  ('Oswin Appollis',          'South Africa'),
  ('Iqraam Rayners',          'South Africa'),
  ('Relebohile Mofokeng',     'South Africa'),
  ('Thapelo Maseko',          'South Africa'),
  ('Tshepang Moremi',         'South Africa'),

  -- Group A · South Korea
  ('Kim Seung-Gyu',           'South Korea'),
  ('Jo Hyeon-woo',            'South Korea'),
  ('Song Bum-keun',           'South Korea'),
  ('Kim Min-jae',             'South Korea'),
  ('Kim Moon-hwan',           'South Korea'),
  ('Seol Young-woo',          'South Korea'),
  ('Cho Yu-min',              'South Korea'),
  ('Lee Tae-seok',            'South Korea'),
  ('Park Jin-seob',           'South Korea'),
  ('Kim Tae-hyeon',           'South Korea'),
  ('Lee Han-beom',            'South Korea'),
  ('Jens Castrop',            'South Korea'),
  ('Lee Ki-hyuk',             'South Korea'),
  ('Lee Jae-sung',            'South Korea'),
  ('Hwang Hee-chan',          'South Korea'),
  ('Hwang In-beom',           'South Korea'),
  ('Lee Kang-in',             'South Korea'),
  ('Paik Seung-ho',           'South Korea'),
  ('Kim Jin-gyu',             'South Korea'),
  ('Lee Dong-gyeong',         'South Korea'),
  ('Bae Jun-ho',              'South Korea'),
  ('Eom Ji-Sung',             'South Korea'),
  ('Yang Hyun-jun',           'South Korea'),
  ('Son Heung-min',           'South Korea'),
  ('Cho Gue-sung',            'South Korea'),
  ('Oh Hyeon-gyu',            'South Korea'),

  -- Group B · Bosnia and Herzegovina
  ('Nikola Vasilj',           'Bosnia and Herzegovina'),
  ('Martin Zlomislic',        'Bosnia and Herzegovina'),
  ('Osman Hadzikic',          'Bosnia and Herzegovina'),
  ('Sead Kolasinac',          'Bosnia and Herzegovina'),
  ('Dennis Hadzikadunic',     'Bosnia and Herzegovina'),
  ('Amar Dedic',              'Bosnia and Herzegovina'),
  ('Nikola Katic',            'Bosnia and Herzegovina'),
  ('Tarik Muharemovic',       'Bosnia and Herzegovina'),
  ('Nihad Mujakic',           'Bosnia and Herzegovina'),
  ('Stjepan Radeljic',        'Bosnia and Herzegovina'),
  ('Nidal Celik',             'Bosnia and Herzegovina'),
  ('Amir Hadziahmetovic',     'Bosnia and Herzegovina'),
  ('Benjamin Tahirovic',      'Bosnia and Herzegovina'),
  ('Armin Gigovic',           'Bosnia and Herzegovina'),
  ('Dzenis Burnic',           'Bosnia and Herzegovina'),
  ('Ivan Basic',              'Bosnia and Herzegovina'),
  ('Esmir Bajraktarevic',     'Bosnia and Herzegovina'),
  ('Amar Memic',              'Bosnia and Herzegovina'),
  ('Ivan Sunjic',             'Bosnia and Herzegovina'),
  ('Kerim Alajbegovic',       'Bosnia and Herzegovina'),
  ('Ermin Mahmic',            'Bosnia and Herzegovina'),
  ('Edin Dzeko',              'Bosnia and Herzegovina'),
  ('Ermedin Demirovic',       'Bosnia and Herzegovina'),
  ('Samed Bazdar',            'Bosnia and Herzegovina'),
  ('Haris Tabakovic',         'Bosnia and Herzegovina'),
  ('Jovo Lukic',              'Bosnia and Herzegovina'),

  -- Group B · Switzerland
  ('Marvin Keller',           'Switzerland'),
  ('Gregor Kobel',            'Switzerland'),
  ('Yvon Mvogo',              'Switzerland'),
  ('Manuel Akanji',           'Switzerland'),
  ('Aurele Amenda',           'Switzerland'),
  ('Eray Comert',             'Switzerland'),
  ('Nico Elvedi',             'Switzerland'),
  ('Luca Jaquez',             'Switzerland'),
  ('Miro Muheim',             'Switzerland'),
  ('Ricardo Rodriguez',       'Switzerland'),
  ('Silvan Widmer',           'Switzerland'),
  ('Michel Aebischer',        'Switzerland'),
  ('Christian Fassnacht',     'Switzerland'),
  ('Remo Freuler',            'Switzerland'),
  ('Ardon Jashari',           'Switzerland'),
  ('Johan Manzambi',          'Switzerland'),
  ('Fabian Rieder',           'Switzerland'),
  ('Djibril Sow',             'Switzerland'),
  ('Ruben Vargas',            'Switzerland'),
  ('Granit Xhaka',            'Switzerland'),
  ('Denis Zakaria',           'Switzerland'),
  ('Zeki Amdouni',            'Switzerland'),
  ('Breel Embolo',            'Switzerland'),
  ('Cedric Itten',            'Switzerland'),
  ('Dan Ndoye',               'Switzerland'),
  ('Noah Okafor',             'Switzerland'),

  -- Group C · Brazil
  ('Alisson',                 'Brazil'),
  ('Ederson',                 'Brazil'),
  ('Weverton',                'Brazil'),
  ('Marquinhos',              'Brazil'),
  ('Danilo Luiz',             'Brazil'),
  ('Alex Sandro',             'Brazil'),
  ('Gabriel Magalhaes',       'Brazil'),
  ('Bremer',                  'Brazil'),
  ('Wesley',                  'Brazil'),
  ('Roger Ibanez',            'Brazil'),
  ('Douglas Santos',          'Brazil'),
  ('Leo Pereira',             'Brazil'),
  ('Casemiro',                'Brazil'),
  ('Lucas Paqueta',           'Brazil'),
  ('Bruno Guimaraes',         'Brazil'),
  ('Fabinho',                 'Brazil'),
  ('Danilo Santos',           'Brazil'),
  ('Neymar',                  'Brazil'),
  ('Vinicius Jr',             'Brazil'),
  ('Raphinha',                'Brazil'),
  ('Gabriel Martinelli',      'Brazil'),
  ('Matheus Cunha',           'Brazil'),
  ('Endrick',                 'Brazil'),
  ('Luiz Henrique',           'Brazil'),
  ('Igor Thiago',             'Brazil'),
  ('Rayan',                   'Brazil'),

  -- Group C · Haiti
  ('Johny Placide',           'Haiti'),
  ('Alexandre Pierre',        'Haiti'),
  ('Josue Duverger',          'Haiti'),
  ('Ricardo Ade',             'Haiti'),
  ('Carlens Arcus',           'Haiti'),
  ('Martin Experience',       'Haiti'),
  ('Jean-Kevin Duverne',      'Haiti'),
  ('Duke Lacroix',            'Haiti'),
  ('Wilguens Paugain',        'Haiti'),
  ('Hannes Delcroix',         'Haiti'),
  ('Keeto Thermoncy',         'Haiti'),
  ('Leverton Pierre',         'Haiti'),
  ('Danley Jean Jacques',     'Haiti'),
  ('Carl Sainte',             'Haiti'),
  ('Jean-Ricner Bellegarde',  'Haiti'),
  ('Woodensky Pierre',        'Haiti'),
  ('Dominique Simon',         'Haiti'),
  ('Duckens Nazon',           'Haiti'),
  ('Frantzdy Pierrot',        'Haiti'),
  ('Derrick Etienne Jr',      'Haiti'),
  ('Louicius Deedson',        'Haiti'),
  ('Ruben Providence',        'Haiti'),
  ('Josue Casimir',           'Haiti'),
  ('Yassin Fortune',          'Haiti'),
  ('Wilson Isidor',           'Haiti'),
  ('Lenny Joseph',            'Haiti'),

  -- Group C · Scotland
  ('Angus Gunn',              'Scotland'),
  ('Craig Gordon',            'Scotland'),
  ('Liam Kelly',              'Scotland'),
  ('Andy Robertson',          'Scotland'),
  ('Kieran Tierney',          'Scotland'),
  ('Anthony Ralston',         'Scotland'),
  ('John Souttar',            'Scotland'),
  ('Scott McKenna',           'Scotland'),
  ('Jack Hendry',             'Scotland'),
  ('Aaron Hickey',            'Scotland'),
  ('Nathan Patterson',        'Scotland'),
  ('Grant Hanley',            'Scotland'),
  ('Dominic Hyam',            'Scotland'),
  ('Scott McTominay',         'Scotland'),
  ('Billy Gilmour',           'Scotland'),
  ('John McGinn',             'Scotland'),
  ('Kenny McLean',            'Scotland'),
  ('Lewis Ferguson',          'Scotland'),
  ('Ryan Christie',           'Scotland'),
  ('Findlay Curtis',          'Scotland'),
  ('Ben Gannon-Doak',         'Scotland'),
  ('Lawrence Shankland',      'Scotland'),
  ('George Hirst',            'Scotland'),
  ('Che Adams',               'Scotland'),
  ('Ross Stewart',            'Scotland'),
  ('Lyndon Dykes',            'Scotland'),

  -- Group D · USA
  ('Matt Turner',             'USA'),
  ('Chris Brady',             'USA'),
  ('Matt Freese',             'USA'),
  ('Sergino Dest',            'USA'),
  ('Chris Richards',          'USA'),
  ('Antonee Robinson',        'USA'),
  ('Auston Trusty',           'USA'),
  ('Miles Robinson',          'USA'),
  ('Tim Ream',                'USA'),
  ('Alex Freeman',            'USA'),
  ('Mark McKenzie',           'USA'),
  ('Joe Scally',              'USA'),
  ('Tyler Adams',             'USA'),
  ('Weston McKennie',         'USA'),
  ('Christian Pulisic',       'USA'),
  ('Sebastian Berhalter',     'USA'),
  ('Cristian Roldan',         'USA'),
  ('Malik Tillman',           'USA'),
  ('Gio Reyna',               'USA'),
  ('Ricardo Pepi',            'USA'),
  ('Brenden Aaronson',        'USA'),
  ('Max Arfsten',             'USA'),
  ('Haji Wright',             'USA'),
  ('Folarin Balogun',         'USA'),
  ('Tim Weah',                'USA'),
  ('Alex Zendejas',           'USA'),

  -- Group E · Curaçao
  ('Eloy Room',               'Curaçao'),
  ('Trevor Doornbusch',       'Curaçao'),
  ('Tyrick Bodak',            'Curaçao'),
  ('Jurien Gaari',            'Curaçao'),
  ('Roshon van Eijma',        'Curaçao'),
  ('Sherel Floranus',         'Curaçao'),
  ('Joshua Brenet',           'Curaçao'),
  ('Shurandy Sambo',          'Curaçao'),
  ('Armando Obispo',          'Curaçao'),
  ('Riechedly Bazoer',        'Curaçao'),
  ('Deveron Fonville',        'Curaçao'),
  ('Leandro Bacuna',          'Curaçao'),
  ('Juninho Bacuna',          'Curaçao'),
  ('Godfried Roemeratoe',     'Curaçao'),
  ('Kevin Felida',            'Curaçao'),
  ('Livano Comenencia',       'Curaçao'),
  ('Ar''jany Martha',         'Curaçao'),
  ('Tyrese Noslin',           'Curaçao'),
  ('Kenji Gorre',             'Curaçao'),
  ('Brandley Kuwas',          'Curaçao'),
  ('Gervane Kastaneer',       'Curaçao'),
  ('Jeremy Antonisse',        'Curaçao'),
  ('Jearl Margaritha',        'Curaçao'),
  ('Jurgen Locadia',          'Curaçao'),
  ('Sontje Hansen',           'Curaçao'),
  ('Tahith Chong',            'Curaçao'),

  -- Group E · Germany
  ('Manuel Neuer',            'Germany'),
  ('Oliver Baumann',          'Germany'),
  ('Alexander Nubel',         'Germany'),
  ('Antonio Rudiger',         'Germany'),
  ('Jonathan Tah',            'Germany'),
  ('Nico Schlotterbeck',      'Germany'),
  ('Nathaniel Brown',         'Germany'),
  ('David Raum',              'Germany'),
  ('Malick Thiaw',            'Germany'),
  ('Waldemar Anton',          'Germany'),
  ('Pascal Gross',            'Germany'),
  ('Joshua Kimmich',          'Germany'),
  ('Leon Goretzka',           'Germany'),
  ('Lennart Karl',            'Germany'),
  ('Jamal Musiala',           'Germany'),
  ('Florian Wirtz',           'Germany'),
  ('Jamie Leweling',          'Germany'),
  ('Aleksandar Pavlovic',     'Germany'),
  ('Maximilian Beier',        'Germany'),
  ('Nadiem Amiri',            'Germany'),
  ('Leroy Sane',              'Germany'),
  ('Angelo Stiller',          'Germany'),
  ('Felix Nmecha',            'Germany'),
  ('Kai Havertz',             'Germany'),
  ('Denis Undav',             'Germany'),
  ('Nick Woltemeade',         'Germany'),

  -- Group E · Ivory Coast
  ('Yahia Fofana',            'Ivory Coast'),
  ('Alban Lafont',            'Ivory Coast'),
  ('Mohamed Kone',            'Ivory Coast'),
  ('Ghislain Konan',          'Ivory Coast'),
  ('Odilon Kossounou',        'Ivory Coast'),
  ('Wilfried Singo',          'Ivory Coast'),
  ('Evan Ndicka',             'Ivory Coast'),
  ('Emmanuel Agbadou',        'Ivory Coast'),
  ('Guela Doue',              'Ivory Coast'),
  ('Ousmane Diomande',        'Ivory Coast'),
  ('Clement Akpa',            'Ivory Coast'),
  ('Franck Kessie',           'Ivory Coast'),
  ('Jean Michael Seri',       'Ivory Coast'),
  ('Ibrahim Sangare',         'Ivory Coast'),
  ('Seko Fofana',             'Ivory Coast'),
  ('Christ Inao Oulai',       'Ivory Coast'),
  ('Parfait Guiagon',         'Ivory Coast'),
  ('Nicolas Pepe',            'Ivory Coast'),
  ('Oumar Diakite',           'Ivory Coast'),
  ('Simon Adingra',           'Ivory Coast'),
  ('Evann Guessand',          'Ivory Coast'),
  ('Amad Diallo',             'Ivory Coast'),
  ('Yan Diomande',            'Ivory Coast'),
  ('Bazoumana Toure',         'Ivory Coast'),
  ('Elye Wahi',               'Ivory Coast'),
  ('Ange Yoan-Bonny',         'Ivory Coast'),

  -- Group F · Japan
  ('Zion Suzuki',             'Japan'),
  ('Keisuke Osako',           'Japan'),
  ('Tomoki Hayakawa',         'Japan'),
  ('Yuto Nagatomo',           'Japan'),
  ('Takehiro Tomiyasu',       'Japan'),
  ('Ko Itakura',              'Japan'),
  ('Shogo Taniguchi',         'Japan'),
  ('Hiroko Ito',              'Japan'),
  ('Yukinari Sugawara',       'Japan'),
  ('Ayumu Seko',              'Japan'),
  ('Tsuyoshi Watanabe',       'Japan'),
  ('Junnosuke Suzuki',        'Japan'),
  ('Wataru Endo',             'Japan'),
  ('Junya Ito',               'Japan'),
  ('Ritsu Doan',              'Japan'),
  ('Daichi Kamada',           'Japan'),
  ('Takefusa Kubo',           'Japan'),
  ('Ao Tanaka',               'Japan'),
  ('Keito Nakamura',          'Japan'),
  ('Kaishu Sano',             'Japan'),
  ('Ayase Ueda',              'Japan'),
  ('Daizen Maeda',            'Japan'),
  ('Koki Ogawa',              'Japan'),
  ('Yuito Suzuki',            'Japan'),
  ('Keisuke Goto',            'Japan'),
  ('Kento Shiogai',           'Japan'),

  -- Group F · Netherlands
  ('Mark Flekken',            'Netherlands'),
  ('Robin Roefs',             'Netherlands'),
  ('Bart Verbruggen',         'Netherlands'),
  ('Nathan Ake',              'Netherlands'),
  ('Denzel Dumfries',         'Netherlands'),
  ('Jorrel Hato',             'Netherlands'),
  ('Jurrien Timber',          'Netherlands'),
  ('Jan Paul van Hecke',      'Netherlands'),
  ('Virgil van Dijk',         'Netherlands'),
  ('Micky van de Ven',        'Netherlands'),
  ('Mats Wieffer',            'Netherlands'),
  ('Ryan Gravenberch',        'Netherlands'),
  ('Frenkie de Jong',         'Netherlands'),
  ('Teun Koopmeijners',       'Netherlands'),
  ('Tijjani Reijnders',       'Netherlands'),
  ('Maarten de Roon',         'Netherlands'),
  ('Guus Til',                'Netherlands'),
  ('Quinten Timber',          'Netherlands'),
  ('Brian Brobbey',           'Netherlands'),
  ('Memphis Depay',           'Netherlands'),
  ('Cody Gakpo',              'Netherlands'),
  ('Justin Kluivert',         'Netherlands'),
  ('Noa Lang',                'Netherlands'),
  ('Donyell Malen',           'Netherlands'),
  ('Crysencio Summerville',   'Netherlands'),
  ('Wout Weghorst',           'Netherlands'),

  -- Group F · Sweden
  ('Kristoffer Nordfeldt',          'Sweden'),
  ('Viktor Johansson',              'Sweden'),
  ('Jacob Widell Zetterstrom',      'Sweden'),
  ('Victor Lindelof',               'Sweden'),
  ('Isak Hien',                     'Sweden'),
  ('Gabriel Gudmundsson',           'Sweden'),
  ('Carl Starfelt',                 'Sweden'),
  ('Emil Holm',                     'Sweden'),
  ('Hjalmar Ekdal',                 'Sweden'),
  ('Daniel Svensson',               'Sweden'),
  ('Gustaf Lagerbielke',            'Sweden'),
  ('Eric Smith',                    'Sweden'),
  ('Elliot Stroud',                 'Sweden'),
  ('Mattias Svanberg',              'Sweden'),
  ('Jesper Karlstrom',              'Sweden'),
  ('Yasin Ayari',                   'Sweden'),
  ('Lucas Bergvall',                'Sweden'),
  ('Besfort Zeneli',                'Sweden'),
  ('Alexander Isak',                'Sweden'),
  ('Viktor Gyokeres',               'Sweden'),
  ('Ken Sema',                      'Sweden'),
  ('Anthony Elanga',                'Sweden'),
  ('Benjamin Nygren',               'Sweden'),
  ('Alexander Bernhardsson',        'Sweden'),
  ('Gustaf Nilsson',                'Sweden'),
  ('Taha Ali',                      'Sweden'),

  -- Group F · Tunisia
  ('Aymen Dahmen',                  'Tunisia'),
  ('Sabri Ben Hessen',              'Tunisia'),
  ('Mouhib Chamakh',                'Tunisia'),
  ('Montassar Talbi',               'Tunisia'),
  ('Dylan Bronn',                   'Tunisia'),
  ('Ali Abdi',                      'Tunisia'),
  ('Yan Valery',                    'Tunisia'),
  ('Mohamed Amine Ben Hamida',      'Tunisia'),
  ('Moutaz Neffati',                'Tunisia'),
  ('Omar Rekik',                    'Tunisia'),
  ('Adem Arous',                    'Tunisia'),
  ('Raed Chikhaoui',                'Tunisia'),
  ('Ellyes Shkiri',                 'Tunisia'),
  ('Hannibal Mejbri',               'Tunisia'),
  ('Anis Ben Slimane',              'Tunisia'),
  ('Mortadha Ben Ouanes',           'Tunisia'),
  ('Ismael Gharbi',                 'Tunisia'),
  ('Hadj Mahmoud',                  'Tunisia'),
  ('Rani Khedira',                  'Tunisia'),
  ('Elias Achouri',                 'Tunisia'),
  ('Firas Chaouat',                 'Tunisia'),
  ('Hazem Mastouri',                'Tunisia'),
  ('Elias Saad',                    'Tunisia'),
  ('Sebastian Tounekti',            'Tunisia'),
  ('Khalil Ayari',                  'Tunisia'),
  ('Rayan Elloumi',                 'Tunisia'),

  -- Group G · Belgium
  ('Thibaut Courtois',              'Belgium'),
  ('Senne Lammens',                 'Belgium'),
  ('Mike Penders',                  'Belgium'),
  ('Thomas Meunier',                'Belgium'),
  ('Timothy Castagne',              'Belgium'),
  ('Arthur Theate',                 'Belgium'),
  ('Zeno Debast',                   'Belgium'),
  ('Maxim De Cuyper',               'Belgium'),
  ('Brandon Mechele',               'Belgium'),
  ('Koni De Winter',                'Belgium'),
  ('Joaquin Seys',                  'Belgium'),
  ('Nathan Ngoy',                   'Belgium'),
  ('Axel Witsel',                   'Belgium'),
  ('Kevin De Bruyne',               'Belgium'),
  ('Youri Tielemans',               'Belgium'),
  ('Hans Vanaken',                  'Belgium'),
  ('Amadou Onana',                  'Belgium'),
  ('Nicolas Raskin',                'Belgium'),
  ('Romelu Lukaku',                 'Belgium'),
  ('Leandro Trossard',              'Belgium'),
  ('Jeremy Doku',                   'Belgium'),
  ('Dodi Lukebakio',                'Belgium'),
  ('Charles De Ketelaere',          'Belgium'),
  ('Alexis Saelemakers',            'Belgium'),
  ('Diego Moreira',                 'Belgium'),
  ('Matias Fernandez-Pardo',        'Belgium'),

  -- Group G · New Zealand
  ('Max Crocombe',                  'New Zealand'),
  ('Alex Paulsen',                  'New Zealand'),
  ('Michael Woud',                  'New Zealand'),
  ('Tim Payne',                     'New Zealand'),
  ('Francis de Vries',              'New Zealand'),
  ('Tyler Bindon',                  'New Zealand'),
  ('Michael Boxall',                'New Zealand'),
  ('Liberato Cacace',               'New Zealand'),
  ('Nando Pijnaker',                'New Zealand'),
  ('Finn Surman',                   'New Zealand'),
  ('Callan Elliot',                 'New Zealand'),
  ('Tommy Smith',                   'New Zealand'),
  ('Joe Bell',                      'New Zealand'),
  ('Matthew Garbett',               'New Zealand'),
  ('Marko Stamenic',                'New Zealand'),
  ('Sarpreet Singh',                'New Zealand'),
  ('Elijah Just',                   'New Zealand'),
  ('Alex Rufer',                    'New Zealand'),
  ('Ben Old',                       'New Zealand'),
  ('Callum McCowatt',               'New Zealand'),
  ('Ryan Thomas',                   'New Zealand'),
  ('Lachlan Bayliss',               'New Zealand'),
  ('Chris Wood',                    'New Zealand'),
  ('Kosta Barbarouses',             'New Zealand'),
  ('Ben Waine',                     'New Zealand'),
  ('Jesse Randall',                 'New Zealand'),

  -- Group H · Cape Verde
  ('Vozinho',                       'Cape Verde'),
  ('Marcio Rosa',                   'Cape Verde'),
  ('CJ dos Santos',                 'Cape Verde'),
  ('Stopira',                       'Cape Verde'),
  ('Roberto Lopes',                 'Cape Verde'),
  ('Joao Paulo',                    'Cape Verde'),
  ('Diney',                         'Cape Verde'),
  ('Logan Costa',                   'Cape Verde'),
  ('Steven Moreira',                'Cape Verde'),
  ('Wagner Pina',                   'Cape Verde'),
  ('Sidny Lopes Cabral',            'Cape Verde'),
  ('Kelvin Pires',                  'Cape Verde'),
  ('Jamiro Monteiro',               'Cape Verde'),
  ('Kevin Pina',                    'Cape Verde'),
  ('Deroy Duarte',                  'Cape Verde'),
  ('Telmo Arcanjo',                 'Cape Verde'),
  ('Laros Duarte',                  'Cape Verde'),
  ('Yannick Semedo',                'Cape Verde'),
  ('Ryan Mendes',                   'Cape Verde'),
  ('Garry Rodrigues',               'Cape Verde'),
  ('Willy Semedo',                  'Cape Verde'),
  ('Jovane Cabral',                 'Cape Verde'),
  ('Gilson Benchimol',              'Cape Verde'),
  ('Dailon Livramento',             'Cape Verde'),
  ('Helio Varela',                  'Cape Verde'),
  ('Nuno da Costa',                 'Cape Verde'),

  -- Group H · Spain
  ('Unai Simon',                    'Spain'),
  ('David Raya',                    'Spain'),
  ('Joan Garcia',                   'Spain'),
  ('Aymeric Laporte',               'Spain'),
  ('Marc Cucurella',                'Spain'),
  ('Marcos Llorente',               'Spain'),
  ('Eric Garcia',                   'Spain'),
  ('Pedro Porro',                   'Spain'),
  ('Alex Grimaldo',                 'Spain'),
  ('Pau Cubarsi',                   'Spain'),
  ('Marc Cubill',                   'Spain'),
  ('Rodri',                         'Spain'),
  ('Fabian Ruiz',                   'Spain'),
  ('Mikel Merino',                  'Spain'),
  ('Pedri',                         'Spain'),
  ('Gavi',                          'Spain'),
  ('Martin Zubimendi',              'Spain'),
  ('Alex Baena',                    'Spain'),
  ('Ferran Torres',                 'Spain'),
  ('Mikel Oyarzabal',               'Spain'),
  ('Dani Olmo',                     'Spain'),
  ('Nico Williams',                 'Spain'),
  ('Lamine Yamal',                  'Spain'),
  ('Yeremy Pino',                   'Spain'),
  ('Borja Iglesias',                'Spain'),
  ('Victor Munoz',                  'Spain'),

  -- Group I · France
  ('Mike Maignan',                  'France'),
  ('Brice Samba',                   'France'),
  ('Robin Risser',                  'France'),
  ('Lucas Digne',                   'France'),
  ('Jules Kounde',                  'France'),
  ('Theo Hernandez',                'France'),
  ('Lucas Hernandez',               'France'),
  ('Dayot Upamecano',               'France'),
  ('William Saliba',                'France'),
  ('Ibrahima Konate',               'France'),
  ('Malo Gusto',                    'France'),
  ('Maxence Lacroix',               'France'),
  ('N''Golo Kante',                 'France'),
  ('Adrien Rabiot',                 'France'),
  ('Aurelien Tchouameni',           'France'),
  ('Manu Kone',                     'France'),
  ('Warren Zaire-Emery',            'France'),
  ('Kylian Mbappe',                 'France'),
  ('Ousmane Dembele',               'France'),
  ('Marcus Thuram',                 'France'),
  ('Bradley Barcola',               'France'),
  ('Michael Olise',                 'France'),
  ('Maghnes Akliouche',             'France'),
  ('Desire Doue',                   'France'),
  ('Rayan Cherki',                  'France'),
  ('Jean-Philippe Mateta',          'France'),

  -- Group I · Norway
  ('Orjan Nyland',                  'Norway'),
  ('Egil Selvik',                   'Norway'),
  ('Sander Tangvik',                'Norway'),
  ('Kristoffer Ajer',               'Norway'),
  ('Julian Ryerson',                'Norway'),
  ('Leo Ostigard',                  'Norway'),
  ('Marcus Holmgren Pedersen',      'Norway'),
  ('David Moller Wolfe',            'Norway'),
  ('Fredrik Andre Bjorkan',         'Norway'),
  ('Torbjorn Heggem',               'Norway'),
  ('Sondre Langas',                 'Norway'),
  ('Henrik Falchener',              'Norway'),
  ('Martin Odegaard',               'Norway'),
  ('Sander Berge',                  'Norway'),
  ('Patrick Berg',                  'Norway'),
  ('Kristian Thorstvedt',           'Norway'),
  ('Morten Thorsby',                'Norway'),
  ('Antonio Nusa',                  'Norway'),
  ('Fredrik Aursnes',               'Norway'),
  ('Oscar Bobb',                    'Norway'),
  ('Jens Petter Hauge',             'Norway'),
  ('Andreas Schjelderup',           'Norway'),
  ('Thelo Aasgaard',                'Norway'),
  ('Erling Haaland',                'Norway'),
  ('Alexander Sorloth',             'Norway'),
  ('Jorgen Strand Larsen',          'Norway'),

  -- Group I · Senegal (status pending, full list provided)
  ('Edouard Mendy',                 'Senegal'),
  ('Mory Diaw',                     'Senegal'),
  ('Yehvann Diouf',                 'Senegal'),
  ('Kalidou Koulibaly',             'Senegal'),
  ('Krepin Diatta',                 'Senegal'),
  ('Moussa Niakhate',               'Senegal'),
  ('Ismail Jakobs',                 'Senegal'),
  ('Abdoulaye Seck',                'Senegal'),
  ('El Hadj Malick Diouf',          'Senegal'),
  ('Antoine Mendy',                 'Senegal'),
  ('Mamadou Sarr',                  'Senegal'),
  ('Ilay Camara',                   'Senegal'),
  ('Moustapha Mbow',                'Senegal'),
  ('Idrissa Gueye',                 'Senegal'),
  ('Pape Gueye',                    'Senegal'),
  ('Pape Matar Sarr',               'Senegal'),
  ('Pathe Siss',                    'Senegal'),
  ('Lamine Camara',                 'Senegal'),
  ('Habib Diarra',                  'Senegal'),
  ('Bara Sapoko Ndiaye',            'Senegal'),
  ('Sadio Mane',                    'Senegal'),
  ('Ismaila Sarr',                  'Senegal'),
  ('Iliman Ndiaye',                 'Senegal'),
  ('Nicolas Jackson',               'Senegal'),
  ('Bamba Dieng',                   'Senegal'),
  ('Cherif Ndiaye',                 'Senegal'),
  ('Ibrahim Mbaye',                 'Senegal'),
  ('Assane Diao',                   'Senegal'),

  -- Group J · Argentina
  ('Emiliano Martinez',             'Argentina'),
  ('Geronimo Rulli',                'Argentina'),
  ('Juan Musso',                    'Argentina'),
  ('Nicolas Otamendi',              'Argentina'),
  ('Nicolas Tagliafico',            'Argentina'),
  ('Nahuel Molina',                 'Argentina'),
  ('Cristian Romero',               'Argentina'),
  ('Gonzalo Montiel',               'Argentina'),
  ('Lisandro Martinez',             'Argentina'),
  ('Leonardo Balerdi',              'Argentina'),
  ('Facundo Medina',                'Argentina'),
  ('Rodrigo De Paul',               'Argentina'),
  ('Leandro Paredes',               'Argentina'),
  ('Giovani Lo Celso',              'Argentina'),
  ('Alexis Mac Allister',           'Argentina'),
  ('Enzo Fernandez',                'Argentina'),
  ('Exequiel Palacios',             'Argentina'),
  ('Valentin Barco',                'Argentina'),
  ('Lionel Messi',                  'Argentina'),
  ('Julian Alvarez',                'Argentina'),
  ('Lautaro Martinez',              'Argentina'),
  ('Nicolas Gonzalez',              'Argentina'),
  ('Thiago Almada',                 'Argentina'),
  ('Giuliano Simeone',              'Argentina'),
  ('Nico Paz',                      'Argentina'),
  ('Jose Manuel Lopez',             'Argentina'),

  -- Group J · Austria
  ('Alexander Schlager',            'Austria'),
  ('Florian Wiegele',               'Austria'),
  ('Patrick Pentz',                 'Austria'),
  ('David Affengruber',             'Austria'),
  ('Kevin Danso',                   'Austria'),
  ('Stefan Posch',                  'Austria'),
  ('David Alaba',                   'Austria'),
  ('Philipp Lienhart',              'Austria'),
  ('Phillipp Mwene',                'Austria'),
  ('Alexander Prass',               'Austria'),
  ('Marco Friedl',                  'Austria'),
  ('Michael Svoboda',               'Austria'),
  ('Xaver Schlager',                'Austria'),
  ('Nicolas Seiwald',               'Austria'),
  ('Marcel Sabitzer',               'Austria'),
  ('Florian Grillitsch',            'Austria'),
  ('Carney Chukwuemeka',            'Austria'),
  ('Romano Schmid',                 'Austria'),
  ('Christoph Baumgartner',         'Austria'),
  ('Konrad Laimer',                 'Austria'),
  ('Patrick Wimmer',                'Austria'),
  ('Paul Wanner',                   'Austria'),
  ('Alessandro Schopf',             'Austria'),
  ('Marko Arnautovic',              'Austria'),
  ('Michael Gregoritsch',           'Austria'),
  ('Sasa Kalajdzic',                'Austria'),

  -- Group K · Colombia
  ('David Ospina',                  'Colombia'),
  ('Camilo Vargas',                 'Colombia'),
  ('Alvaro Montero',                'Colombia'),
  ('Davinson Sanchez',              'Colombia'),
  ('Santiago Arias',                'Colombia'),
  ('Yerry Mina',                    'Colombia'),
  ('Daniel Munoz',                  'Colombia'),
  ('Johan Mojica',                  'Colombia'),
  ('Jhon Lucumi',                   'Colombia'),
  ('Deiver Machado',                'Colombia'),
  ('Willer Ditta',                  'Colombia'),
  ('James Rodriguez',               'Colombia'),
  ('Jefferson Lerma',               'Colombia'),
  ('Juan Fernando Quintero',        'Colombia'),
  ('Jhon Arias',                    'Colombia'),
  ('Richard Rios',                  'Colombia'),
  ('Kevin Castano',                 'Colombia'),
  ('Jorge Carrastal',               'Colombia'),
  ('Jaminton Campaz',               'Colombia'),
  ('Juan Portilla',                 'Colombia'),
  ('Gustavo Puerta',                'Colombia'),
  ('Luis Diaz',                     'Colombia'),
  ('Jhon Cordoba',                  'Colombia'),
  ('Luis Suarez',                   'Colombia'),
  ('Cucho Hernandez',               'Colombia'),
  ('Andres Gomez',                  'Colombia'),

  -- Group K · DR Congo
  ('Lionel Mpasi',                  'DR Congo'),
  ('Timothy Fayulu',                'DR Congo'),
  ('Matthieu Epolo',                'DR Congo'),
  ('Chancel Mbemba',                'DR Congo'),
  ('Arthur Masuaku',                'DR Congo'),
  ('Gedeon Kalulu',                 'DR Congo'),
  ('Joris Kayembe',                 'DR Congo'),
  ('Dylan Batubinsika',             'DR Congo'),
  ('Axel Tuanzebe',                 'DR Congo'),
  ('Aaron Wan-Bissaka',             'DR Congo'),
  ('Rocky Bushiri',                 'DR Congo'),
  ('Steve Kapuadi',                 'DR Congo'),
  ('Meschak Elia',                  'DR Congo'),
  ('Samuel Moutoussamy',            'DR Congo'),
  ('Edo Kayembe',                   'DR Congo'),
  ('Charles Pickel',                'DR Congo'),
  ('Gael Kakuta',                   'DR Congo'),
  ('Noah Sadiki',                   'DR Congo'),
  ('Nathanael Mbuku',               'DR Congo'),
  ('Ngal''ayel Mukau',              'DR Congo'),
  ('Brian Cipenga',                 'DR Congo'),
  ('Cedric Bakambu',                'DR Congo'),
  ('Theo Bongonba',                 'DR Congo'),
  ('Fiston Mayele',                 'DR Congo'),
  ('Yoane Wissa',                   'DR Congo'),
  ('Simon Banza',                   'DR Congo'),

  -- Group K · Portugal
  ('Diogo Costa',                   'Portugal'),
  ('Jose Sa',                       'Portugal'),
  ('Rui Silva',                     'Portugal'),
  ('Joao Cancelo',                  'Portugal'),
  ('Diogo Dalot',                   'Portugal'),
  ('Ruben Dias',                    'Portugal'),
  ('Goncalo Inaco',                 'Portugal'),
  ('Nuno Mendes',                   'Portugal'),
  ('Renato Veiga',                  'Portugal'),
  ('Matheus Nunes',                 'Portugal'),
  ('Nelson Semedo',                 'Portugal'),
  ('Tomas Araujo',                  'Portugal'),
  ('Bruno Fernandes',               'Portugal'),
  ('Joao Neves',                    'Portugal'),
  ('Bernardo Silva',                'Portugal'),
  ('Vitinha',                       'Portugal'),
  ('Ruben Neves',                   'Portugal'),
  ('Samu Costa',                    'Portugal'),
  ('Cristiano Ronaldo',             'Portugal'),
  ('Rafael Leao',                   'Portugal'),
  ('Pedro Neto',                    'Portugal'),
  ('Francisco Conceicao',           'Portugal'),
  ('Joao Felix',                    'Portugal'),
  ('Goncalo Guedes',                'Portugal'),
  ('Goncalo Ramos',                 'Portugal'),
  ('Francisco Trincao',             'Portugal'),

  -- Group L · Croatia
  ('Dominik Livakovic',             'Croatia'),
  ('Dominik Kotarski',              'Croatia'),
  ('Ivor Pandur',                   'Croatia'),
  ('Josko Gvardiol',                'Croatia'),
  ('Duje Caleta-Car',               'Croatia'),
  ('Josip Stanisic',                'Croatia'),
  ('Marin Pongracic',               'Croatia'),
  ('Martin Erlic',                  'Croatia'),
  ('Luka Vuskovic',                 'Croatia'),
  ('Luka Modric',                   'Croatia'),
  ('Mateo Kovacic',                 'Croatia'),
  ('Mario Pasalic',                 'Croatia'),
  ('Nikola Vlasic',                 'Croatia'),
  ('Luka Sucic',                    'Croatia'),
  ('Martin Baturina',               'Croatia'),
  ('Kristijan Jakic',               'Croatia'),
  ('Petar Sucic',                   'Croatia'),
  ('Nikola Moro',                   'Croatia'),
  ('Toni Fruk',                     'Croatia'),
  ('Ivan Perisic',                  'Croatia'),
  ('Andrej Kramaric',               'Croatia'),
  ('Ante Budimir',                  'Croatia'),
  ('Marco Pasalic',                 'Croatia'),
  ('Petar Musa',                    'Croatia'),
  ('Igor Matanovic',                'Croatia'),

  -- Group L · England
  ('Jordan Pickford',               'England'),
  ('Dean Henderson',                'England'),
  ('James Trafford',                'England'),
  ('Dan Burn',                      'England'),
  ('Marc Guehi',                    'England'),
  ('Reece James',                   'England'),
  ('Ezri Konsa',                    'England'),
  ('Tino Livramento',               'England'),
  ('Nico O''Reilly',                'England'),
  ('Jarrell Quansah',               'England'),
  ('Djed Spence',                   'England'),
  ('John Stones',                   'England'),
  ('Elliot Anderson',               'England'),
  ('Jude Bellingham',               'England'),
  ('Eberechi Eze',                  'England'),
  ('Jordan Henderson',              'England'),
  ('Kobbie Mainoo',                 'England'),
  ('Declan Rice',                   'England'),
  ('Morgan Rogers',                 'England'),
  ('Harry Kane',                    'England'),
  ('Anthony Gordon',                'England'),
  ('Noni Madueke',                  'England'),
  ('Marcus Rashford',               'England'),
  ('Bukayo Saka',                   'England'),
  ('Ivan Toney',                    'England'),
  ('Ollie Watkins',                 'England'),

  -- Group L · Panama
  ('Orlando Mosquera',              'Panama'),
  ('Luis Mejia',                    'Panama'),
  ('Cesar Samudio',                 'Panama'),
  ('Cesar Blackman',                'Panama'),
  ('Jorge Gutierrez',               'Panama'),
  ('Amir Murillo',                  'Panama'),
  ('Fidel Escobar',                 'Panama'),
  ('Andres Andrade',                'Panama'),
  ('Edgardo Farina',                'Panama'),
  ('Jose Cordoba',                  'Panama'),
  ('Eric Davis',                    'Panama'),
  ('Jiovany Ramos',                 'Panama'),
  ('Roderick Miller',               'Panama'),
  ('Anibal Godoy',                  'Panama'),
  ('Carlos Harvey',                 'Panama'),
  ('Cristian Martinez',             'Panama'),
  ('Jose Luis Rodriguez',           'Panama'),
  ('Cesar Yanis',                   'Panama'),
  ('Yoel Barcenas',                 'Panama'),
  ('Azarias Londono',               'Panama'),
  ('Adalberto Carrasquilla',        'Panama'),
  ('Alberto Quintero',              'Panama'),
  ('Ismael Diaz',                   'Panama'),
  ('Cecilio Waterman',              'Panama'),
  ('Jose Fajardo',                  'Panama'),
  ('Tomas Rodriguez',               'Panama')
)
insert into players (name, team_id)
select s.name, t.id
from seed s
join teams t on t.name = s.team
on conflict (team_id, name) do nothing;
